name: CI/CD Pipeline - OTI Students

on:
  push:
    branches: [ "main" ]

jobs:
  test-code:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar c칩digo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt
          pip install httpx pytest

      - name: Correr Pruebas Autom치ticas
        env:
            TEST_MODE: "True"
        run: pytest

  deploy-to-server:
    needs: test-code
    runs-on: self-hosted
    
    steps:
      - name: Descargar c칩digo nuevo
        uses: actions/checkout@v3

      - name: Crear archivo .env en Producci칩n
        run: |
          Remove-Item -Path .env -ErrorAction SilentlyContinue
          
          $content = @"
          DB_USER=user
          DB_PASSWORD=user_pass
          DB_NAME=db_estudiantes
          DB_HOST=db
          DB_PORT=3306
          MYSQL_ROOT_PASSWORD=root_admin
          "@
          
          Set-Content -Path .env -Value $content -Encoding Ascii

      - name: Reiniciar Contenedores Docker
        run: |
          docker compose down
          docker compose up -d --build
          
      - name: Limpieza
        run: docker system prune -f